language: node_js
node_js:
  - stable
install:
  - npm install
  - npm install -g codecov
script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -t :76c6d7aa-975e-458d-b194-77c3cc74579c
